### ISSUE TITLE
[META] phase 3

### ISSUE THREAD

**Issue by oliverklee** [phpList/core#127]
- [x] #159 support for PHP 7.2
- [x] #239 provide the source code language in the code snippets in the README
- [x] #124, #241 make sure everything is fine both with the lowest as well as highest version of the dependencies
- [x] #252 add a model and repository for subscriptions
- [x] research whether a m:n association can have an automatic creation date
- [x] #246, #264 use a shared integration test for the core and the REST API
- [x] #261 use touchDatabaseTable in the ModificationDateOfNewModel and fix any bugs in touchDatabaseTable with this
- [ ] rework the login code so a web login for non-superuser admins will be possible
- [x] block authentication for disabled admins
- [ ] add badges for code coverage
- [ ] research how to nicely display the code quality, e.g., with badges?
- [ ] #247, #??? add system tests for all three environments
- [ ] document how to run the dev server for all 4 sub projects
- [ ] #237 rework the documentation
- [ ] add and configure Symfony caching
- [ ] add and configure Doctrine caching
- [ ] disable all caching for the development and testing contexts (including route caching
